/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import org.neuroph.core.NeuralNetwork;
import org.neuroph.core.data.DataSet;
import org.neuroph.core.data.DataSetRow;
import org.neuroph.nnet.MultiLayerPerceptron;

/**
 *
 * @author UTNG
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPromedio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        chkPrimera = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtReprobadas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbEconomia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spnInasistencias = new javax.swing.JSpinner();
        cmbSalud = new javax.swing.JComboBox<>();
        cmbEstadoEmo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnDiagnosticar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JTextField();
        lblExito = new javax.swing.JLabel();
        lblFracaso = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 155, 155));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Diágnostico de deserción");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Promedio Acedémico:");

        txtPromedio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPromedio.setText("0.0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Materias reprobadas:");

        chkPrimera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkPrimera.setSelected(true);
        chkPrimera.setText("Sí");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("¿Primera Opción?");

        txtReprobadas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtReprobadas.setText("0");
        txtReprobadas.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Estatus económico:");

        cmbEconomia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbEconomia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Deficiente", "Regular", "Buena" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Porcentaje de inasistencias: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Salud:");

        spnInasistencias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spnInasistencias.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));

        cmbSalud.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbSalud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Deficiente", "Regular", "Buena" }));

        cmbEstadoEmo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbEstadoEmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Deficiente", "Regular", "Buena" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Estado emocional:");

        btnDiagnosticar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDiagnosticar.setText("Diagnosticar");
        btnDiagnosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        txtResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtResultado.setText(" ");

        lblExito.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblExito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/verde.png"))); // NOI18N
        lblExito.setText(".");

        lblFracaso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFracaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/rojo.png"))); // NOI18N
        lblFracaso.setText(".");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtResultado)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblExito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(lblFracaso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFracaso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnLimpiar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpiar1.setText("Créditos");

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalir.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbEconomia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtReprobadas)
                                    .addComponent(spnInasistencias)
                                    .addComponent(chkPrimera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPromedio))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDiagnosticar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLimpiar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbSalud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbEstadoEmo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkPrimera)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnDiagnosticar)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtReprobadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLimpiar))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEconomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnLimpiar1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spnInasistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbEstadoEmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiagnosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticarActionPerformed

        NeuralNetwork nn = new MultiLayerPerceptron(7,20,1);
        DataSet ds = new DataSet(7,1);
        
        ds.addRow(new DataSetRow(new double[]{-1,	0,	1,	-1,	1,	1,	-1},new double[]{1}));
        ds.addRow(new DataSetRow(new double[]{-1,	0,	1,	-1,	1,	1,	1},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{-1,	0,	1,	1,	-1,	0,	0},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{-1,	1,	0,	0,	0,	-1,	1},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{0,	0,	0,	-1,	0,	1,	-1},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{0,	0,	0,	-1,	1,	-1,	1},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{0,	0,	0,	0,	0,	0,	0},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{0,	0,	0,	1,	0,	0,	1},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{0,	0,	0,	1,	1,	0,	1},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{0,	0,	1,	1,	0,	0,	-1},new double[]{1}));
        ds.addRow(new DataSetRow(new double[]{0,	1,	1,	-1,	0,	1,	1},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{0,	1,	1,	0,	0,	0,	0},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{0,	1,	1,	1,	1,	1,	1},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{1,	0,	0,	1,	1,	1,	-1},new double[]{1}));
        ds.addRow(new DataSetRow(new double[]{1,	0,	1,	0,	1,	0,	1},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{1,	1,	0,	0,	-1,	1,	-1},new double[]{1}));
        ds.addRow(new DataSetRow(new double[]{1,	1,	0,	0,	1,	1,	-1},new double[]{1}));
        ds.addRow(new DataSetRow(new double[]{1,	1,	0,	1,	-1,	-1,	-1},new double[]{1}));
        ds.addRow(new DataSetRow(new double[]{1,	1,	0,	1,	1,	1,	1},new double[]{0}));
        ds.addRow(new DataSetRow(new double[]{1,	1,	1,	1,	1,	0,	1},new double[]{0}));
        
        
        nn.learn(ds);
        
        int aa;         //
        int fo;         //
        int naa;        //
        int ecs;        //
        int nac;        //
        int f;          //
        int ems;        //
       
        double promedio;
        double[] netOutput;
        int porcentaje;
        
        promedio = Double.parseDouble(txtPromedio.getText());
        
        if(promedio < 8){
            aa=-1;
        }else if(promedio < 9){
            aa = 0;
        }else{
            aa = 1;
        }
        
        fo  = (chkPrimera.isSelected()?1:0);
        naa = (Integer.parseInt(txtReprobadas.getText())>0?0:1);
        ecs = cmbEconomia.getSelectedIndex()-2;
        
        porcentaje = Integer.parseInt(spnInasistencias.getValue().toString());
        
        if(porcentaje > -1 ){
            nac = 1;
        }else if(porcentaje < 15){
            nac = 0;
        }else{
            nac = -1;
        }
        
        f = cmbSalud.getSelectedIndex()-2;
        ems = cmbEstadoEmo.getSelectedIndex()-2;
        
        nn.setInput(aa,fo,naa,ecs,nac,f,ems);
        
        netOutput = nn.getOutput();
        
        
        if(netOutput[0] < 0.49){
            txtResultado.setText("Riesgo normal");
            lblFracaso.setVisible(false);
        }else{
            txtResultado.setText("Riesgo elevado");
            lblExito.setVisible(false);
        }
        
        
        
        
    }//GEN-LAST:event_btnDiagnosticarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtPromedio.setText("0.0");
        chkPrimera.setSelected(true);
        txtReprobadas.setText("0");
        cmbEconomia.setSelectedIndex(0);
        spnInasistencias.setValue(0);
        cmbSalud.setSelectedIndex(0);
        cmbEstadoEmo.setSelectedIndex(0);
        txtResultado.setText("");
        lblFracaso.setVisible(true);
        txtResultado.setText("");
        lblExito.setVisible(true);
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiagnosticar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkPrimera;
    private javax.swing.JComboBox<String> cmbEconomia;
    private javax.swing.JComboBox<String> cmbEstadoEmo;
    private javax.swing.JComboBox<String> cmbSalud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblExito;
    private javax.swing.JLabel lblFracaso;
    private javax.swing.JSpinner spnInasistencias;
    private javax.swing.JTextField txtPromedio;
    private javax.swing.JTextField txtReprobadas;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
